### PR TITLE
Translated up to "What YOU need to know" title

### PR DESCRIPTION
**Pull request by pipeaw**
Native speaker here. Thanks for starting the translation

### CODE REVIEW

**Comment by JPeisach** [comment]
Reading through it, and with another ML translator, looks good! :D

**Comment by JPeisach** [comment]
@MrBased uhh i did a big dum, i'm not good with git rebasing and i think i just squashed the commit - aka, now it doesnt say you committed anything

ill try to figure out what i did wrong so next time you're credited

**Comment by JPeisach** [comment]
Okay, github has a sync fork button, best feature ever, I wont do it again. Sorry, I do want to make sure you're credited :)

**Comment by pipeaw** [comment]
@ItzSwirlz its fine. maybe I'll continue translating later

**Pull request merged**
