### PR TITLE
README spanish translation complete

### PR DESCRIPTION
**Pull request by pipeaw**
@ItzSwirlz

### CODE REVIEW

**Comment by pipeaw** [comment]
There was a conflict (resolved) in a paragraph that was already translated but it wasn't quite right. lmk if you want me to point out the mistakes.

**Comment by JPeisach** [comment]
> There was a conflict (resolved) in a paragraph that was already translated but it wasn't quite right. lmk if you want me to point out the mistakes.

Point out the mistakes, grill me, you're the native speaker. Try syncing the fork again

**Comment by pipeaw** [comment]
> > There was a conflict (resolved) in a paragraph that was already translated but it wasn't quite right. lmk if you want me to point out the mistakes.
> 
> Point out the mistakes, grill me, you're the native speaker. Try syncing the fork again

@ItzSwirlz  nah chill. basically its just that if you translate word by word something originally written in english to spanish then the contents of the message can get distorted or difficult to read (thankfully, that doesn't mean you won't be comprehended). Just difference in expressions between languages. I know its difficult so don't worry, glad to help

EDIT: conflicts solved. its mergin time

**Comment by JPeisach** [comment]
Yay! I'm going to have to take a pause from translating stuff currently for my other tech projects, but I'll continue!

**Pull request merged**
